version: 2.1

jobs:
  build-kernel:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: bash build-kernel.sh
      - store_artifacts:
          path: bzImage
  
  build-busybox:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: bash build-busybox.sh
      - store_artifacts:
          path: initramfs.cpio.gz

workflows:
  micro-kernel:
    jobs:
      - build-kernel
      - build-busybox
